def try_func():
    try:
        pass
    except ValueError:
        pass
